<?php
/**
 * View list product
 * PHP version 5.3.9
 * @author nqtrung
 * @copyright Kobe Digital Labo, Inc
 * @since 2015/05/18
 */
//---get URL;
//---list data
$session = Globals::getSession();

if(isset($session->nameProduct)){
    unset($session->nameProduct);
}

$req = Zend_Controller_Front::getInstance()->getRequest();
$params = $req->getParams();
$header['recommendation_order'] = array('title'=>'表示順','hoption'=>'style="width:80px;"  ','option'=>'class="code"  ', 'input' => array('type' => 'text', 'name' => 'recommendation_order', 'attr' => 'maxlength="3" style="width:40px"'));
$header['menuCode'] = array('title'=>'商品ID','hoption'=>'style="width:80px;"  ','option'=>'class="code"  ','sort'=>'menuCode','order'=>'desc');
$header['category1_name'] = array('title'=>'カテゴリー','hoption'=>'style="width:280px;"  ','option'=>'class="text"  ','sort'=>'category1_name','order'=>'desc');
$header['itemName'] = array('title'=>'商品名','hoption'=>'style=""  ','option'=>'class="text"  ','sort'=>'itemName','order'=>'desc');
$header['price'] = array('title'=>'商品単価','hoption'=>'style="width:80px;"  ','option'=>'class="curry"  ','sort'=>'price','order'=>'desc');

$data = $this->dataProductList;
$listData = new Application_Model_Datagrid($data,$header, 1, array('select_all' => 
	array('title' => 'おすすめ', 'checked' => 'recommend', 'check_all_event' => 'checkAll(this)', 'check_all_name' => 'chk_select_all', 'check_row_name' => 'chk_check_row')));
$pageNavi_html = $listData->creatPageNavigation();
$pageLink_html = $listData->creatPageLink();
$list_html = $listData->createList(array(), array('values' => isset($this->data['recommendation_order']) ? array('recommendation_order' => $this->data['recommendation_order']) : array()), array('menuCode' => array('id' => 'h_row', 'name' => 'h_row[]')));

?>
<style>
.datagrid-row {
    height: 50px;
}

.count {
    width: 70px !important;
}
</style>
<form name="frm_recommendproducts" id="frm_recommendproducts" method="post" action="">
    <?php echo $this->csrf; ?>
    <div id="page-title">
            おすすめ設定
    </div>
    <?php if (!empty($this->message)) : ?>
	<?php if ($this->success) : ?>
	    <div style="padding: 0.3em;"> 
		<ul class="message-section">
		    <?php foreach ($this->message as $msg): ?>
			<?php if (!is_array($msg)) : ?>
			    <li><?php echo $this->escape($msg); ?></li>
			<?php endif; ?>
		    <?php endforeach; ?>
		</ul>
	    </div>
	    <div class="clear"></div>
	<?php else : ?>
	    <div style="padding:0.3em;">				
		<ul class="error-section">
		    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
		    <?php foreach ($this->message as $msg): ?>
			<?php if (!is_array($msg)) : ?>
			    <li><?php echo $this->escape($msg); ?></li>
			<?php endif; ?>
		    <?php endforeach; ?>
		</ul>
	    </div>
	    <div class="clear"></div>
	<?php endif; ?>
	<?php endif; ?>
<?php
//echo $search_html;
$itemName = isset($params['item']) ? $this->escape($params['item']) : '';
$pricegt = isset($params['pricegt']) ?  $this->escape($params['pricegt']) : '';
$pricelt = isset($params['pricelt']) ?  $this->escape($params['pricelt']) : '';
$category1_name = isset($params['category']) ?  $this->escape($params['category']) : '';

//---get data Category
$csv = new Application_Model_Category();
$data_Categ = $csv->getDataJson1();
$optionCategory1 = $csv->createOptionCategory($data_Categ['rows'], array('value' => 'code', 'title' => 'name'), $category1_name);
?>
    <div id="filter">
                <div>
                        <div class="lft">検索条件</div>					
                        <div class="lft" style="margin: 0 5px 0 10px"><input id="display-search"  type="checkbox"  /></div>
                        <div class="lft">表示切替</div>
                        <div class="clr">&nbsp;</div>
                </div>
                <div id="searchForm">

                        <table class="data-filter" border="1">					
                                <tr class="odd">
                                        <td class="label" width="100px">商品名</td>
                                        <td width="220px"><input id="item" maxlength="85" name="item" class="name" type="text" value="<?php echo $itemName; ?>" />
                                            <span class="guide">前方後方一致検索</span>
                                        </td>
                                </tr>
                                <tr class="even">
                                        <td class="label">販売価格</td>
                                        <td><input id="pricegt" name="pricegt" class="price" type="text" maxlength="10"  value="<?php echo $pricegt; ?>" />～<input id="pricelt" name="pricelt" class="price" maxlength="10"  type="text" value="<?php echo $pricelt; ?>" />
                                            <span class="guide">前方後方一致検索</span>
                                        </td>      
                                </tr>
                                <tr class="odd">
                                        <td class="label">カテゴリー</td>
                                        <td>
                                            <select id="category" name="category"  class="name">
                                                <?php echo $optionCategory1 ?>
                                            </select>
                                        </td>
                                </tr>	
								<tr class="even">
                                        <td class="label">おすすめのみ</td>
                                        <td><input type="checkbox" id="recommend" name="recommend" style="width:13px;margin-left: 3px" <?php echo isset($params['recommend']) ? "checked='checked'" : '' ?>/></td>
                                </tr>
                        </table>
                        <div class="btn-search">
                                <input class="input-btn" type="button" name="btnSearch" id="btnSearch" value="検索" />
                        </div>
                </div>
                <div class="clr">&nbsp;</div>	
                <br/>
                <table class="data-filter" border="1">
                    <tr class="odd">
                        <td class="label" width="100px"><span>おすすめタイトル</span></td>
                        <td width="220px">
                            <input id="recommendationTitle" name="recommendationTitle" type="textbox" class="input" value="<?php echo $this->data['recommendationTitle'] ?>" style="float: left; margin: 3px 5px 0 0;">
                        </td>
                    </tr>
                </table>
    </div>
    <div class="clr">&nbsp;</div>	
	
<?php
    echo $pageNavi_html;
    echo $pageLink_html;
    echo $list_html;
?>
 
<?php
    if (count($data) > 0) {
?>
<div class="btn-container">
    <div class="edit-btn-article">
        <input type="button" class="input_btn_update rft" id="btnsave-bottom" alt="反映" value="反映">
    </div>
</div>    
<?php
    }
?>
</form>    
<div class="clear"></div>

<script>

    $('#btnSearch').click(function(){
        searchSubmit();
    });
    function searchSubmit(){
        var url_search = '';
        if($('#item').val() != ''){
            url_search = url_search + '/item/' + $('#item').val();
        }
        if($('#pricegt').val() != ''){
            url_search = url_search + '/pricegt/' + $('#pricegt').val();
        }
        if($('#pricelt').val() != ''){
            url_search = url_search + '/pricelt/' + $('#pricelt').val();
        }
        if($('#category').val() != ''){
            url_search = url_search + '/category/' + $('#category').val();
        }
		if($('#recommend').attr('checked') === 'checked'){
            url_search = url_search + '/recommend/on';
        }
        
        location.href = '/recommendproducts/index' + url_search;
    }
    
    $('#rows').change(function(){
        var url_search = '';
        url_search = '/rows/' + $('#rows').val();
        location.href = '<?php unset($params['rows']); $params['page'] = 1; echo $listData->getCreateURL('/recommendproducts/index',$params) ?>'+url_search;
    });
    
    $("#display-search").click(function () {
            $("#searchForm").toggle();
            if ($('#display-search').attr('checked'))
            {
                    $.cookie('CookieKeyVisibleSearchFormItems', 1, {path:'/'});
            }
            else
            {
                    $.cookie('CookieKeyVisibleSearchFormItems', 0, {path:'/'});
            }
    });
       
    if ($.cookie('CookieKeyVisibleSearchFormItems') == 1)
    {
            $('#display-search').attr('checked', 'checked');
            $("#searchForm").show();
    }
    else
    {
            $("#searchForm").hide();
    }
    
    $('.combo-text').removeAttr('style');
    $('.combo-text').val('<?php echo $category1_name; ?>');
    
	function checkAll(obj) {
		$("input[name='" + $(obj).attr('child') + "']").prop('checked', obj.checked);
	}
	
	$('#btnsave-bottom').click(function() {
        $('#frm_recommendproducts')[0].action = '/recommendproducts/save';
        $('#frm_recommendproducts')[0].submit();
    });

    $(document).ready(function() {	                
        //---Enter form search.
                
         $('#item').keypress(function(event){
                if ( event.which == 13 ) {
                    searchSubmit();
                }
        });
        $('#pricegt').keypress(function(event){
                if ( event.which == 13 ) {
                    searchSubmit();
                }
        });
        $('#pricelt').keypress(function(event){
                if ( event.which == 13 ) {
                    searchSubmit();
                }
        });
        $('#category').keypress(function(event){
                if ( event.which == 13 ) {
                    searchSubmit();
                }
        });
		
		$('th.count').css('width', '45px');
    });

</script>


