<?php
/**
 * Add category form
 * PHP version 5.3.9
 * @author Phan Quoc Bao
 * @copyright Kobe Digital Labo, Inc
 * @since 2014/04/24
 */
?>
<?php 

$req = Zend_Controller_Front::getInstance()->getRequest();
$session = Globals::getSession();

$modelList_product = new Application_Model_Datagrid();
$params = $req->getParams();
$url = $modelList_product->getCreateURL('/video/index',$params);
if(isset($session->backUrl)){
    $url = $session->backUrl;
}else{
    $session->backUrl = $url;
}

if(!isset($session->nameVideo)){
    $session->nameVideo = $this->escape($this->data['name']);
}
?>
<div class="section">
	<form name="frm_edit" id="frm_edit" method="post" action="" enctype="multipart/form-data">
		<?php echo $this->csrf; ?>
		<div id="page-title">
			<?php echo $session->nameVideo; ?>の編集
		</div>
                <?php if (!empty($this->message)) : ?>
			<?php if ($this->success) : ?>
                            <div style="padding: 0.3em;"> 
				<ul class="message-section">
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php else : ?>
			    <div style="padding:0.3em;">				
				<ul class="error-section">
				    <li><strong>ファイルの登録に失敗しました。</strong></li>
				    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php endif; ?>
	        <?php endif; ?>
                        <div class="edit-tbl-wrapper">
                            <table class="edit-detail-tbl common-detail-tbl">
                                        <?php $indexRow = 1; ?>
<!--                                    <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                            <th class="common-tbl-row " style="width:160px;" ><span>動画名</span></th>
                                            <td width="450px">-->
                                                <input type="hidden" readonly="readonly" style="width:230px" id="name" name="name" maxlength="32" value="<?php if (isset($this->data['name'])): echo $this->escape($this->data['name']); endif ?>" />
<!--                                            </td>
                                            <td class="guide"></td>
                                    </tr>-->
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row require " width="100px"><span>ファイル</span></th>
                                                <td width="450px">
                                                        <input type="file" id="videos" size="50" name="videos[]" />
                                                        <span class="guide">動画サイズの上限: 100.0MB</span>
                                                </td>
                                        </tr>
                                </table>
                        </div>
                        <div class="btn-container">
                                <div class="edit-btn-article">
                                        <span class="btn btn-l btn-action lft"><a href="<?php echo $url; ?>"><span class="ic-normal">一覧に戻る</span></a></span>	
					<span class="btn btn-d btn-delete rft"><a href="javascript:void(0)" id="btndelete-bottom" ><span class="ic-delete">削除</span></a></span>
                                        <input type="button" class="input_btn_update rft" id="btnsave-bottom" alt="更新" value="更新">					
                                </div>
                        </div>
        </form>
</div>

<script>
    var frm_edit        = '#frm_edit';
    var btnsave        = '#btnsave-bottom';

    $(btnsave).bind('click', function(){
        var files = $('input[name|="videos[]"]');
        var isEmptyFile = false;
        files.each(function(){
            if ($(this).val() != '') {
                isEmptyFile = true;
                return true;
            }
        });
        
        if (isEmptyFile == true) {
            fieldObj = document.getElementById("videos");
            if(checkFile(fieldObj)){
                $(frm_edit)[0].action = '/video/editexecute';
                $(frm_edit).submit();
            }           
            
        } else {
            alert('<?php echo $this->alertSelect; ?>');
            return false;
        }
    });
    
    function checkFile(fieldObj)
    {
        var FileName  = fieldObj.value;
        FileName = FileName.substr(FileName.lastIndexOf('\\')+1);
        var FileExt = FileName.substr(FileName.lastIndexOf('.')+1);
        var FileSize = fieldObj.files[0].size;
        
		var fileName = '<?php echo $session->nameVideo; ?>';
        var listNameFileExit = '<?php echo $this->listNameExit; ?>';
        arrFileName = listNameFileExit.split(',');
        
        var allowExtensions = '<?php echo $this->allowExtensions; ?>';
        arrExt = allowExtensions.split(',');
        var maxSize = <?php echo $this->maxSize; ?>;
        //---check exit file
        if(fileName !== FileName && arrFileName.indexOf(FileName) > 0){
            alert('<?php echo $this->msgE701_Existed; ?>'.replace("%s", FileName));
            return false;
        }
        
        //---check allowExtensions
        if( arrExt.indexOf(FileExt) <= 0 ){
            alert('<?php echo $this->msgE701_FileExtensionFalse; ?>'.replace("%value%", FileName));
            return false;
        }
        
        //---check maxSize
        if( FileSize > maxSize){
            var msgError = '<?php echo $this->msgE701_FileSizeMax; ?>'.replace("%value%", FileName);
            alert(msgError.replace("%max%", maxSize) );
            return false;
        }
        
        return true;
    }
    
    $('#btndelete-bottom').click(function(){
        if (!confirm('<?php echo sprintf($this->confirmDel, $session->nameVideo );?>')) return;
            $(frm_edit)[0].action = '/video/delete/name/<?php if (isset($this->data['name'])): echo $this->escape($this->data['name']); endif ?>';
            $(frm_edit).submit();
    });

 </script>
