<?php
/**
 * Add category form
 * PHP version 5.3.9
 * @author Nguyen Thi Tho
 * @copyright Kobe Digital Labo, Inc
 * @since 2012/07/23
 */

 $data_kind = isset($this->data['kind'])?$this->data['kind']:'';
?>

<div class="section">
	<form name="frm_add" id="frm_add" method="post" action="" enctype="multipart/form-data">
		<?php echo $this->csrf; ?>
		<div id="page-title">
			新規カテゴリー登録
		</div>
                <?php if (!empty($this->message)) : ?>
			<?php if ($this->success) : ?>
                            <div style="padding: 0.3em;"> 
				<ul class="message-section">
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php else : ?>
			    <div style="padding:0.3em;">				
				<ul class="error-section">
				    <li><strong>カテゴリーの登録に失敗しました。</strong></li>
				    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php endif; ?>
	        <?php endif; ?>
                        <div class="edit-tbl-wrapper">
                            <table class="edit-detail-tbl common-detail-tbl">
                                        <?php $indexRow = 1; ?>
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row require " width="100px"><span>カテゴリー種別</span></th>
                                                <td width="450px">
                                                        <select id="kind" name="kind" >
                                                            <option value="1" <?php if( $data_kind == 1):?> selected="selected"<?php endif;?>>1</option>
                                                            <option value="2" <?php if( $data_kind == 2):?> selected="selected"<?php endif;?>>2</option>
                                                        </select>
                                                        <span class="guide">1:メインカテゴリー<br/>
													2:サブカテゴリー<br/>
													通常は1を選択してください。</span>
                                                </td>
                                        </tr>
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row require"><span>カテゴリー名</span></th>
                                                <td>
                                                       <input type="text" size="50" id="name" name="name" maxlength="85"  value="<?php if (isset($this->data['name'])) { echo $this->escape($this->data['name']);} ?>" />
                                                       <span class="guide">85文字以内。例）ドリンク</span>
                                                </td>
                                        </tr>
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row "><span>カテゴリー画像</span></th>
                                                <td>
                                                    <input id="image" type="file" name="image[]" class="input" style="width:322px">
                                                    <span class="guide">カテゴリーの画像を設定してください。<br/>
													ファイルサイズは2MB以内。<br/>
													推奨サイズは512x384(px)です。</span>
                                                </td>
                                        </tr>
                                </table>
                        </div>
                        <div class="btn-container">
                                <div class="edit-btn-article">
                                        <input id="btnsave" type="button" class="input_btn" role="button" value="登録" />
                                </div>
                        </div>
        </form>
</div>

<script>
    var frm_add        = '#frm_add';
    var btnsave        = '#btnsave';

    $(btnsave).bind('click', function(){
//        if (!confirm('<?php // echo $this->confirmAdd;?>')) return;
        $(frm_add)[0].action = '/category/addexecute';
        $(frm_add).submit();
    });

 </script>
