<?php
/**
 * import category
 * PHP version 5.3.9
 * @author Nguyen Thi Tho
 * @copyright Kobe Digital Labo, Inc
 * @since 2012/08/02
 */
?>
<?php
    $req = Zend_Controller_Front::getInstance()->getRequest();
    $session = Globals::getSession();
    $modelList_category = new Application_Model_Datagrid();
    $params = $req->getParams();
    $url = $modelList_category->getCreateURL('/category/index',$params);
    if(isset($session->backUrl)){
        $url = $session->backUrl;
    }else{
        $session->backUrl = $url;
    }
?>
<div class="section">
	<form name="frm_upload" id="frm_upload" method="post" action="" enctype="multipart/form-data">
		<?php echo $this->csrf; ?>
		<div id="page-title">
			カテゴリーデータ取込
		</div>
                <?php if (!empty($this->message)) : ?>
			<?php if ($this->success) : ?>
                            <div style="padding: 0.3em;"> 
				<ul class="message-section">
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php else : ?>
			    <div style="padding:0.3em;">				
				<ul class="error-section">
				    <li><strong>カテゴリーデータ取込に失敗しました。</strong></li>
				    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php endif; ?>
	        <?php endif; ?>
                        <div class="edit-tbl-wrapper">
                            <table class="edit-detail-tbl common-detail-tbl">
                                        <?php $indexRow = 1; ?>
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row " width="100px"><span>更新方法</span></th>
                                                <td width="450px">
                                                        <label for="upload_type-update"><input type="radio" checked="checked" value="update" id="upload_type-update" name="upload_type">上書き更新</label>&nbsp;&nbsp;
                                                        <label for="upload_type-new"><input type="radio" value="new" id="upload_type-new" name="upload_type">入替え更新</label>                                                
                                                        <span class="guide">【上書き更新】<br/>
                                                                    ・同一IDのデータは更新。新規データは追加登録します。<br/>
                                                                    &nbsp; <br/>
                                                                    【入替え更新】<br/>
                                                                    ・全てのデータを削除した後、全データを再登録します。</span>
                                                </td>
                                        </tr>
										<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row " width="100px"><span>文字コード</span></th>
                                                <td width="450px">
                                                        <label for="upload_charset-sjis"><input type="radio" <?php echo ($this->data['upload_charset'] == 'SJIS')?'checked="checked"':''; ?>  value="SJIS" id="upload_charset-sjis" name="upload_charset">SHIFT-JIS</label>&nbsp;&nbsp;
                                                        <label for="upload_charset-utf8"><input type="radio" <?php echo ($this->data['upload_charset'] == 'UTF-8')?'checked="checked"':''; ?> value="UTF-8" id="upload_charset-utf8" name="upload_charset">UTF-8</label>                                                
                                                        <input type="hidden" id="upload_charset_utf8" name="upload_charset_utf8" >
                                                        <span class="guide">【SHIFT-JIS】<br/>
                                                                   ・EXCEL等のソフトで編集する場合はこちらを選択してください。</span>
                                                </td>
                                        </tr>
                                        <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                                <th class="common-tbl-row require"><span>ファイル</span></th>
                                                <td>
                                                       <input id="page_csv" type="file" name="page_csv" class="input" size="60"><br>
                                                </td>
                                        </tr>
                                </table>
                        </div>
                        <div class="btn-container">
                            <div class="edit-btn-article">
                                    <!--<input type="submit" class="input_btn lft" alt="一覧に戻る" value="一覧に戻る">-->
                                    <span class="btn btn-l btn-action lft"><a href="<?php echo $url; ?>"><span class="ic-normal">一覧に戻る</span></a></span>	
                                    <input type="button" class="input_btn_update rft" id="btnsave-bottom" alt="アップロード" value="アップロード" onclick="uploadCsv()">					
                            </div>
                        </div>
        </form>
</div>
<script>
    var frm_upload = '#frm_upload';

    function uploadCsv(){
//        if (validateForm() == true) {
//            if (!confirm('<?php // echo $this->confiemImpCsv; ?>')) return;
            $(frm_upload).attr('action', '/category/uploadcsv');
            $(frm_upload).submit();
//        }
    }
    
    function validateForm() {
        if ($('#page_csv').val() == ''){
            alert('<?php echo $this->alertImp; ?>');
            return false;
        }
        
        // CSVアップロード処理
        if ($('input[name=upload_type]:checked').val() == undefined){
            alert('<?php echo $this->alertImportType; ?>');
            return false;
        }
        
        return true;
    }
    
    function downloadCsv() {
        $(frm_upload).attr('action', '/category/download-csv');
        $(frm_upload).submit();
    }
</script>



