<?php
/**
 * Add subcomment form
 * PHP version 5.3.9
 * @author Nguyen Dinh Bao
 * @copyright Kobe Digital Labo, Inc
 * @since 2014/04/22
 */
$req = Zend_Controller_Front::getInstance()->getRequest();
$session = Globals::getSession();

$modelList_product = new Application_Model_Datagrid();
$params = $req->getParams();
$url = $modelList_product->getCreateURL('/subcomment/index', $params);
if (isset($session->backUrl)) {
    $url = $session->backUrl;
} else {
    $session->backUrl = $url;
}

if(!isset($session->nameCustomerOrder)){
    $session->nameCustomerOrder = $this->escape($this->data['guidance']);
}
?>
<form name="frm_edit" id="frm_edit" method="post" enctype="multipart/form-data">
    <?php echo $this->csrf; ?>
    <div id="page-title">
        <?php echo $session->nameCustomerOrder ?>の編集
    </div>

    <?php if (!empty($this->message)) : ?>
            <?php if ($this->success) : ?>
                <div style="padding: 0.3em;"> 
                    <ul class="message-section">
                        <?php foreach ($this->message as $msg): ?>
                            <?php if (!is_array($msg)) : ?>
                                <li><?php echo $this->escape($msg); ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="clear"></div>
            <?php else : ?>
                <div style="padding:0.3em;">				
                    <ul class="error-section">
                        <li><strong>カスタムオーダーの登録に失敗しました。</strong></li>
                        <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
                        <?php foreach ($this->message as $msg): ?>
                            <?php if (!is_array($msg)) : ?>
                                <li><?php echo $this->escape($msg); ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="clear"></div>
            <?php endif; ?>
    <?php endif; ?>
                
    <?php
    //$prod_name = isset($params['prod_code']) ? trim($params['prod_code']) : '';
    //---get data Category
    $csv = new Application_Model_Index();
    $data_Prod = $csv->getDataJson();
    ?>       
    <div class="detail-tbl-wrapper">
        <table class="data-filter" border="1" width="100%">					
            <tr class="odd">
                <td class="label" style="width: 300px"><span>カスタムオーダーグループID</span></td>
                <td><input type="text" value="<?php if (isset($this->data['no'])) { echo $this->escape($this->data['no']);}?>" maxlength="32" name="no" id="no" style="width:80px" readonly="readonly">
                    <span class="guide">カスタムオーダーグループIDは自動採番されます。</span>
                </td>
            </tr>
            <tr class="even">
                <td class="label require" style="width: 300px"><span>カスタムオーダーグループ名</span></td>
                <td><input id="guidance" name="guidance" class="name" type="text" style="width:420px" value="<?php if (isset($this->data['guidance'])) { echo $this->escape($this->data['guidance']);}?>" />
                    <span class="guide">30文字以内 例）飲み方</span>
                </td>
            </tr>
        </table>				
    </div>

    <div class="clr">&nbsp;</div>

    <div id="data-grid">
        <table id="CustomerOrder" class="grid" cellpadding="0" cellspacing="0" border="1" width="100%">
            <thead>
                <tr>
                    <th style="width: 100px !important"></th>						
                    <th>カスタムオーダー名</th>
                </tr>
            </thead>
            <tbody>
                <?php       
                $row = Globals::getApplicationConfig('subcomment')->max_list;          
                $count = 1;
                if($this->msg) {
                    $count_menu = count($this->data)-2;
                    for($i=1; $i<=$row; $i++){
                        if(isset($this->data['menu'.$i])){
                            if($data_Prod['rows']!='') {
                                $optionProd = $csv->createOptionProd($data_Prod['rows'], array('value' => 'menuCode', 'title' => 'itemName'), $this->escape($this->data['menu'.$i]));
                            }
                            else {
                                $optionProd = '';
                            }                                     
                            $class = ($count%2) ? 'odd' : 'even';
                            echo '<tr class="'.$class.'">
                                    <td class=" sorting_1">'.$count.'</td>
                                    <td class="">                        
                                        <select id="menu'.$i.'" name="menu'.$i.'"  class="name">
                                            <option value=""></option>
                                            '.$optionProd.'
                                        </select>
                                        <span class="guide">商品を選択してください。</span>
                                    </td>
                                </tr>';
                            $count ++;
                        }                       
                    }
                }
                else {
                    $count_menu = count(array_filter($this->data))-2;
                    for($i=1; $i<=$row; $i++){
                        if(isset($this->data['menu'.$i]) && $this->data['menu'.$i] != null && $this->data['menu'.$i] != 0) {
                            if($data_Prod['rows']!='') {
                                $optionProd = $csv->createOptionProd($data_Prod['rows'], array('value' => 'menuCode', 'title' => 'itemName'), $this->escape($this->data['menu'.$i]));
                            }
                            else {
                                $optionProd = '';
                            }                                    
                            $class = ($count%2) ? 'odd' : 'even';
                            echo '<tr class="'.$class.'">
                                    <td class=" sorting_1">'.$count.'</td>
                                    <td class="">                        
                                        <select id="menu'.$i.'" name="menu'.$i.'"  class="name">
                                            <option value=""></option>
                                            '.$optionProd.'
                                        </select>
                                        <span class="guide">商品を選択してください。</span>
                                    </td>
                                </tr>';
                            $count ++;
                        }
                    }
                }                
                ?>                   
            </tbody>									
        </table>				
    </div>	        
    <div>		
        <input type="button" id="AddCustomOrder" onclick="addRow()" value="1レコード追加" />
    </div>
        
    <div class="btn-container">
        <div class="edit-btn-article">
            <span class="btn btn-l btn-action lft"><a href="<?php echo $url; ?>"><span class="ic-normal">一覧に戻る</span></a></span>	
            <span class="btn btn-d btn-delete rft"><a id="btndelete-bottom" href="javascript:void(0);"><span class="ic-delete">削除</span></a></span>
            <input type="button" value="更新" alt="更新" id="btnsave" class="input_btn_update rft">					
        </div>
    </div>
</form>
<script>
    var count = <?php echo $count_menu+1 ?>;

    $(document).ready(function() {
        $('table#CustomerOrder').dataTable({
            'bFilter': false,
            'bInfo': false,
            'bSort': false,
            'bPaginate': false,
            "oLanguage": {
                "sEmptyTable": "カスタムオーダーグループは登録されていません。"
            }
        });
        
        if(count == <?php echo Globals::getApplicationConfig('subcomment')->max_list+1 ?>){
            document.getElementById("AddCustomOrder").disabled = true;
        }
        // Add initial row
        //addRow();
    } );
    
    function addRow() {
        <?php
            if($data_Prod['rows']!='') {
                $optionProd = $csv->createOptionProd($data_Prod['rows'], array('value' => 'menuCode', 'title' => 'itemName'), '');
            }
            else {
                $optionProd = '';
            }
        ?> 
        $('table#CustomerOrder').dataTable().fnAddData( [				
            '<div style="text-align: center">'+count+'</div>',
            '<select id="menu' + count + '" name="menu' + count + '"  class="name"><option value=""></option><?php echo $optionProd ?></select><span class="guide">商品を選択してください。</span>'
        ] );       
        count++;
        if(count == <?php echo Globals::getApplicationConfig('subcomment')->max_list+1 ?>){
            document.getElementById("AddCustomOrder").disabled = true;
        }
    }
    
    function deleteRow (index) {
        alert(index);
        if (count != 1) {
            $("table#CustomerOrder").dataTable().fnDeleteRow(index);
            count--;
        }
    }
    
    //Get data fill suggest1 combobox
    var frm_edit = ('#frm_edit');
    var btnsave  = ('#btnsave');

    $(btnsave).bind('click', function(){
        //if (!confirm('<?php echo $this->confirmEdit; ?>')) return;       
        $(frm_edit)[0].action = '/subcomment/editexecute';
        $(frm_edit).submit();
    });
    
    $('#btndelete-bottom').click(function(){
        if (!confirm('<?php echo sprintf($this->confirmDel, $session->nameCustomerOrder );?>')) return;
            $(frm_edit)[0].action = '/subcomment/delete/id_edit/<?php if (isset($this->data['no'])): echo $this->escape($this->data['no']); endif ?>';
            $(frm_edit).submit();
    });
    
</script>
