<?php
/**
 * Add printer group form
 * PHP version 5.3.9
 * @author nqtrung
 * @copyright Kobe Digital Labo, Inc
 * @since 2014/12/18
 */
?>

<div class="section">
	<form name="frm_add" id="frm_add" method="post" action="">
		<?php echo $this->csrf; ?>
		<div id="page-title">
			プリンターグループ登録
		</div>
            <?php if (!empty($this->message)) : ?>
			<?php if ($this->success) : ?>
                            <div style="padding: 0.3em;"> 
				<ul class="message-section">
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php else : ?>
			    <div style="padding:0.3em;">				
				<ul class="error-section">
				    <li><strong>プリンターグループの登録に失敗しました。</strong></li>
				    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php endif; ?>
	        <?php endif; ?>
                        <div class="edit-tbl-wrapper">
                            <table class="edit-detail-tbl common-detail-tbl">
                                        <?php $indexRow = 1; ?>
                                <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                    <th class="common-tbl-row require" width="100px"><span>グループ名</span></th>
                                    <td width="450px">
                                        <input type='text' size="40" id="groupName" name="groupName" maxlength="10" 
                                            value="<?php if (isset($this->data['groupName'])) { echo $this->escape($this->data['groupName']); } ?>" />
                                        <span class="guide">プリンター設定の解りやすい名称を入力（10文字以内）</span>
                                    </td>
                                </tr>
                                <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                    <th class="common-tbl-row" width="100px"><span>会計伝票プリンター</span></th>
                                    <td>
                                        <input type='text' size="40" id="IPAddress" name="IPAddress" maxlength="15" 
                                            value="<?php if (isset($this->data['IPAddress'])) { echo $this->escape($this->data['IPAddress']); } ?>" />
                                    </td>
                                </tr>
                                <?php foreach ($this->categoryData as $value): ?>
                                <tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
                                        <th class="common-tbl-row "><span><?php echo $this->escape($value['name']); ?></span></th>
                                        <td>
                                            <input type='text' size="40" name="printerIP[]" maxlength="45" 
                                                value="<?php if (isset($this->printerIPs[$value['code']])) { echo $this->escape($this->printerIPs[$value['code']]); } ?>" />
                                            <input type="hidden" name="hPrinterIP[]" value="<?php echo $value['code'] ?>"/>
                                            <input type="hidden" name="msg<?php echo $value['code'] ?>" value=""/>
                                            <span class="guide">このカテゴリー商品を印刷するプリンターIPアドレス入力</span>
                                        </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                        <div class="btn-container">
                                <div class="edit-btn-article">
                                        <input id="btnsave" type="button" class="input_btn" role="button" value="登録" />
                                </div>
                        </div>
        </form>
</div>

<script>
    var frm_add        = '#frm_add';
    var btnsave        = '#btnsave';

    $(btnsave).bind('click', function(){
        $(frm_add)[0].action = '/printergroup/addexecute';
        $(frm_add).submit();
    }); 
 </script>
