<?php
/**
 * Video list
 * PHP version 5.3.9
 * @author nqtrung
 * @copyright Kobe Digital Labo, Inc
 * @since 2014/12/18
 */
?>
<?php 

//---get URL;
//---list data
$session = Globals::getSession();
if(isset($session->backUrl)){
    unset($session->backUrl);
}

if(isset($session->nameVideo)){
    unset($session->nameVideo);
}

$req = Zend_Controller_Front::getInstance()->getRequest();
$params = $req->getParams();
$header['id'] = array('title'=>'プリンターグループID','hoption'=>'style="width:150px;"  ','option'=>'style="text-align:center;  ','sort'=>'name','order'=>'desc');
$header['printerGroupName'] = array('title'=>'プリンターグループ名','hoption'=>'style=""  ','option'=>'class="text"  ','sort'=>'','order'=>'desc');

$data = $this->data;

$listData = new Application_Model_Datagrid($data, $header);

$pageNavi_html = $listData->creatPageNavigation();

$pageLink_html = $listData->creatPageLink();
$list_html = $listData->createList(array('id' => array('action'=>'/printergroup/edit','namepost'=>'id','value'=>'id') ));

?>
<form name="frm_printergroup_list" id="frm_category" method="get" action="">    

    <div id="page-title">
           プリンターグループ一覧
    </div>
        <?php if (!empty($this->message)) : ?>
                <?php if ($this->success) : ?>
                    <div style="padding: 0.3em;"> 
                        <ul class="message-section">
                            <?php foreach ($this->message as $msg): ?>
                                <?php if (!is_array($msg)) : ?>
                                    <li><?php echo $this->escape($msg); ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="clear"></div>
                <?php else : ?>
                    <div style="padding:0.3em;">				
                        <ul class="error-section">
                            <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
                            <?php foreach ($this->message as $msg): ?>
                                <?php if (!is_array($msg)) : ?>
                                    <li><?php echo $this->escape($msg); ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="clear"></div>
                <?php endif; ?>
        <?php endif; ?>                    
    <div class="detail-btn">
            <span class="btn btn-m btn-action"><a href="<?php echo $listData->getCreateURL('/printergroup/add',$params) ?>"><span class="ic-add">新規追加</span></a></span>
    </div>

    <?php 
    echo $pageNavi_html;
    echo $pageLink_html;
    echo $list_html;
    ?> 
</form>
<div class="clear"></div>
<script>

    $('#rows').change(function(){
        var url_search = '';
        url_search = '/rows/' + $('#rows').val();
        location.href = '<?php unset($params['rows']); $params['page'] = 1; echo $listData->getCreateURL('/printergroup/index',$params) ?>'+url_search;
    });

</script>
