<?php
/**
 * Edit product form
 * PHP version 5.3.9
 * @author Nguyen Thi Tho
 * @copyright Kobe Digital Labo, Inc
 * @since 2012/07/16
 */
$req = Zend_Controller_Front::getInstance()->getRequest();
$session = Globals::getSession();

$modelList_product = new Application_Model_Datagrid();
$params = $req->getParams();
$url = $modelList_product->getCreateURL('/product/index',$params) . (isset($this->data['menuCode']) ? '#r' . $this->data['menuCode'] : '');
if(isset($session->backUrl)){
    $url = $session->backUrl;
}else{
    $session->backUrl = $url;
}

//---get data Category => list box
$csv = new Application_Model_Category();
$data_Categ = $csv->getDataJson1();
$optionCategory1   = $csv->createOptionCategory($data_Categ['rows'],array('value'=>'code','title'=>'name'),isset($this->data['category1_code'])?$this->escape($this->data['category1_code']):'','');

//---Get data Topping => list box
$csv = new Application_Model_Topping();
$data_Topping = $csv->getData();
$optionTopping   = $csv->createOptionToppiong($data_Topping,array('value'=>'itemToppingGroupId','title'=>'itemToppingGroupName'),isset($this->data['itemToppingGroupId'])?$this->escape($this->data['itemToppingGroupId']):'','');

//---get data Product
$data_Product = $this->indexModel->getDataJson();
$optionSuggest1Product   = $this->indexModel->createOptionProd($data_Product['rows'], array('value' => 'menuCode', 'title' => 'itemName'), isset($this->data['suggest1'])?$this->escape($this->data['suggest1']):'');
$optionSuggest2Product   = $this->indexModel->createOptionProd($data_Product['rows'], array('value' => 'menuCode', 'title' => 'itemName'), isset($this->data['suggest2'])?$this->escape($this->data['suggest2']):'');
$optionSuggest3Product   = $this->indexModel->createOptionProd($data_Product['rows'], array('value' => 'menuCode', 'title' => 'itemName'), isset($this->data['suggest3'])?$this->escape($this->data['suggest3']):'');

//---set session nameProduct if session null    
if(!isset($session->nameProduct)){
    $session->nameProduct = $this->escape($this->data['itemName']);
}
//---set session imageproduct
if(!isset($session->imageDelete)){
    $session->imageDelete = isset($this->data['image'])?$this->data['image']:'';
}
?>
<div class="section">
	<form name="frm_edit_product" id="frm_edit_product" method="post" action="" enctype="multipart/form-data">
		<?php echo $this->csrf; ?>
		<div id="page-title">
			<?php echo $session->nameProduct; ?>の編集
		</div>
                <input type="hidden" id="no" name="no" value="<?php echo $this->escape($this->data['no']); ?>" />
		<?php if (!empty($this->message)) : ?>
			<?php if ($this->success) : ?>
                            <div style="padding: 0.3em;"> 
				<ul class="message-section">
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php else : ?>
			    <div style="padding:0.3em;">				
				<ul class="error-section">
				    <li><strong>商品の編集に失敗しました。</strong></li>
				    <li><strong>エラーが発生しました。エラーメッセージをご確認下さい。</strong></li>
				    <?php foreach ($this->message as $msg): ?>
					<?php if (!is_array($msg)) : ?>
					    <li><?php echo $this->escape($msg); ?></li>
					<?php endif; ?>
				    <?php endforeach; ?>
				</ul>
			    </div>
			    <div class="clear"></div>
			<?php endif; ?>
	        <?php endif; ?>
        <div class="btn-container" style="width:99.2%">
        <div class="edit-btn-article">
            <span class="btn btn-l btn-action lft"><a href="<?php echo $url; ?>"><span class="ic-normal">一覧に戻る</span></a></span>	
            <span class="btn btn-d btn-delete rft"><a href="javascript:void(0)" id="btndelete-bottom" class="btndelete-bottom" ><span class="ic-delete">削除</span></a></span>
                                <input type="button" class="input_btn_update rft" id="btnsave-top" alt="更新" value="更新">					
        </div>
        </div>
		<div class="edit-tbl-wrapper">
			<table class="edit-detail-tbl common-detail-tbl extenion">
				<?php $indexRow = 1; ?>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row " style="width:160px;" ><span>商品ID</span></th>
					<td width="650px">
						<input type="text" style="width:80px" id="menuCode" name="menuCode" maxlength="32" value="<?php if (isset($this->data['menuCode'])): echo $this->escape($this->data['menuCode']); endif ?>" />
                        <span class="guide">10文字以内。商品を一意に識別できるコードを入力してください。例）1111</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row require"><span>商品名</span></th>
					<td>
						<input type="text" size="50" id="itemName" name="itemName" maxlength="85" value="<?php if (isset($this->data['itemName'])) { echo $this->escape($this->data['itemName']);}?>" />
                        <span class="guide">85文字以内。例）タラ白子のムニエル<br/>
						@#$%^&"\'+=<>{}[\],は使用しないでください。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row require"><span>カテゴリー名</span></th>
					<td>
						<select id="category1_code" name="category1_code" style="160px;">
                                                    <?php echo $optionCategory1; ?>
                                                </select>
						<!--<input type="hidden" id="category1_name" name="category1_name">-->
                        <span class="guide">カテゴリーを選択してください。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row require"><span>商品単価</span></th>
					<td>
						<input type="text" style="width:80px;text-align: right;" id="price" name="price" maxlength="10" value="<?php if (isset($this->data['price']) && $this->data['price'] != '') { echo $this->escape($this->data['price']); }else{ echo '0';} ?>"/>
						<label>円</label>
                        <span class="guide">数字8桁以内。</span>
					</td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">カスタムオーダー</th>
					<td>
						<?php echo $this->formSelect('SCP5', (!empty($this->data['SCP5']) ? $this->data['SCP5'] : null), null, $this->dataSubComment) ?>
                        <span class="guide">カスタムオーダーが存在する場合、選択してください。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">トッピンググループ</th>
					<td>
						<select id="itemToppingGroupId" name="itemToppingGroupId" style="160px;">
                                                    <?php echo $optionTopping; ?>
                                                </select>
                        <span class="guide">トッピングが存在する場合、選択してください。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">商品画像</th>
					<td class="text_input">
						<?php $hasImage = !empty($this->data['image']); ?>
						<div id="div_image_product" class="edit_img" style="display:<?php echo $hasImage ? 'inline-block' : 'none'; ?>">
							<a class="fancybox-effects-a" href="/product/image/name/<?php echo $this->escape($this->data['image']) ?>">
								<img width="200px" src="/product/image/name/<?php echo $this->escape($this->data['image']) ?>" />
							</a>
							<div id="delete_image" class="del_btn" style="cursor:pointer"><img title="削除する" width="30px" src="/images/del.png"/></div>
							<input type="hidden" id="image_product" name="image_product" value="<?php echo (!empty($this->data['image']) ? $this->escape($this->data['image']) : '') ?>">
							<input type="hidden" name="image_product_old" value="<?php echo (!empty($this->data['image']) ? $this->escape($this->data['image']) : '') ?>">
						</div>
						<input id="p_image_file" type="file" name="p_image_file[]" class="input" style="width:322px;display:<?php echo $hasImage ? 'none' : 'block'; ?>">						
                        <span class="guide" <?php echo $hasImage ? 'style="padding-top:185px"' : '' ?>>商品画像を設定してください。<br/>
						ファイルサイズは2MB以内。<br/>
						推奨サイズは512x384(px)です。<br/>
						画像を削除したい場合は画像の上にカーソルをおくと×マークが画像の左上に出るのでクリックします。<br/>
						すると画像が消えるので、その状態で更新すると画像が削除されます。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">
						<label>説明</label>
					</th>
					<td>
						<textarea id="desc" name="desc" rows="10" col="50" maxlength="1000" style="width:290px"><?php if (isset($this->data['desc'])) { echo $this->escape($this->data['desc']); } ?></textarea>
                        <span class="guide">1000文字以内で商品の説明を入力してください。<br/>
						iPad上では目安として36文字で改行します。<br/>@#$%^&"\'+=<>{}[\],は使用しないでください。</span>
                    </td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">
						<label>関連商品1</label>
					</th>
					<td>
						<select id="suggest1" name="suggest1" style="160px;">
							<option value=""></option>
							<?php echo $optionSuggest1Product; ?>
						</select>
                        <span class="guide">関連商品が存在する場合、選択してください。</span>
					</td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">
						<label>関連商品2</label>
					</th>
					<td>
						<select id="suggest2" name="suggest2" style="160px;">
							<option value=""></option>
							<?php echo $optionSuggest2Product; ?>
						</select>
                        <span class="guide">関連商品が存在する場合、選択してください。</span>
					</td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">
						<label>関連商品3</label>
					</th>
					<td>
						<select id="suggest3" name="suggest3" style="160px;">
							<option value=""></option>
							<?php echo $optionSuggest3Product; ?>
						</select>
                        <span class="guide">関連商品が存在する場合、選択してください。</span>
					</td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">
					<th class="common-tbl-row">取扱い時間</th>
					<td>
						<table class="sub-input">
							<tbody><tr>
								<th align="right" style="width:50%">
                                                                    <div style="width: 28%;float: left;">
                                                                                開始時刻&nbsp;
                                                                                <input type="text" style="width:114px" id="startTime" name="startTime" maxlength="5"
                                                                                value="<?php
                                                                                 if (isset($this->data['startTime'])
                                                                                     && $this->data['startTime'] != ''
                                                                                 ) {
                                                                                     echo $this->escape(substr($this->data['startTime'], 0, 2) . ':' . substr($this->data['startTime'], 2, 2));
                                                                                 } else {
                                                                                     echo '';
                                                                                 }
                                                                                 ?>"/>
                                                                        </div>
                                                                        <div style="width:  32%;float: left;">
                                                                                終了時刻&nbsp;
                                                                                <input   type="text" style="width:114px" id="endTime" name="endTime" maxlength="5"
                                                                                value="<?php
                                                                                 if (isset($this->data['endTime'])
                                                                                     && $this->data['endTime'] != ''
                                                                                 ) {
                                                                                     echo $this->escape(substr($this->data['endTime'], 0, 2) . ':' . substr($this->data['endTime'], 2, 2));
                                                                                 }?>" />
                                                                        </div>
                                                                        <div style="clear: both;float: left; margin-left: 10px; text-align: left;">
                                                                            <input type="hidden" name="Time" id="Time">
                                                                        </div>
									
								</th>
								
							</tr>							
							</tbody>
						</table>
                        <span class="guide">取扱い開始時刻と終了時刻が存在する場合、入力してください。</span>
					</td>
				</tr>
				<tr class="<?php echo $indexRow % 2 == 0 ? 'odd' : 'even';$indexRow++; ?>">					
					<th class="common-tbl-row">プリンター</th>
					<td>
						<table class="sub-input">
							<tbody>
                                                            <tr>
                                                                    <th align="right" style="width:50%;">
                                                                        <div style="width: 28%;float: left;">
                                                                                IP&nbsp;
                                                                                <input type="text" style="width:100px" id="PrinterIP" name="PrinterIP" value="<?php if (isset($this->data['PrinterIP'])) { echo $this->escape($this->data['PrinterIP']);}?>" />
                                                                        </div>
                                                                        <div style="width:  32%;float: left;">
                                                                                ポート&nbsp;
                                                                                <input type="text" style="width:100px" id="PrinterPort" name="PrinterPort" maxlength="10" value="<?php if (isset($this->data['PrinterPort'])) { echo $this->escape($this->data['PrinterPort']); }?>" />
                                                                        </div>
                                                                        <div style="clear: both;float: left; margin-left: 10px; text-align: left;">
                                                                            <input type="hidden" name="Printer" id="Printer">
                                                                        </div>
                                                                    </th>
                                                                    
                                                            </tr>

							</tbody>
						</table>
                        <span class="guide">商品を印字するプリンターのIPアドレス。<br/>
						ポートは通常9100。</span>
					</td>
				</tr>			
			</table>
		</div>
                <div class="btn-container">
				<div class="edit-btn-article">
					<span class="btn btn-l btn-action lft"><a href="<?php echo $url; ?>"><span class="ic-normal">一覧に戻る</span></a></span>	
					<span class="btn btn-d btn-delete rft"><a href="javascript:void(0)" id="btndelete-bottom" class="btndelete-bottom" ><span class="ic-delete">削除</span></a></span>
                                        <input type="button" class="input_btn_update rft" id="btnsave-bottom" alt="更新" value="更新">					
				</div>
                </div>
	</form>
</div>
	
<script>
    var endTime        = '#endTime';
    var startTime      = '#startTime';
    var price          = '#price';
    var image          = '#image';
    var loadImage      = '#loadImage';
    var btnsave_t      = '#btnsave-top';
    var btnsave_b      = '#btnsave-bottom';
    var frm_edit_product = '#frm_edit_product';
	var delete_image	= '#delete_image';
	var startTime		= '#startTime';
	var endTime		= '#endTime';

	$(document).ready(function() {	
		$('.fancybox').fancybox();
		$(startTime).change();
		$(endTime).change();

		// Change title type, overlay closing speed
		$(".fancybox-effects-a").fancybox({
			helpers: {
				title : {
					type : 'outside'
				},
				overlay : {
					speedOut : 0
				}
			}
		});
	});

    function saveProduct() {
        $(frm_edit_product)[0].action = '/product/editexecute';
        $(frm_edit_product).submit();
    }

    $(btnsave_t).bind('click', function(){
        saveProduct();
    });
	
    $(btnsave_b).bind('click', function(){
        saveProduct();
    });

    $(delete_image).bind('click', function() {
        $('#div_image_product').css('display', 'none');
        $('#p_image_file').css('display', 'block');
        $('#image_product').val('');
    });
    
    $(function(){
        $(endTime).timespinner({
            showSeconds:false
        });
    })
    
    $(function(){
        $(startTime).timespinner({
            showSeconds:false
        });
    })
	
     $(function(){
         $(price).numberbox({
            min:0,
            precision:0
        });
        $(startTime).removeAttr('style');
        $(startTime).css('width', '100px');
        $(endTime).removeAttr('style');
        $(endTime).css('width', '100px');
 		$('.spinner-arrow-up').removeAttr('style');
		$('.spinner-arrow-down').removeAttr('style');
    });

    $('#menuCode').attr('readonly', 'readonly');
    $('.btndelete-bottom').click(function(){
        
        //---Delete Product
        if (!confirm('<?php echo sprintf($this->confirmDel, $session->nameProduct );?>')) return;
            $(frm_edit_product)[0].action = '/product/delete/id_edit/<?php if (isset($this->data['menuCode'])): echo $this->escape($this->data['menuCode']); endif ?>';
            $(frm_edit_product).submit();
    });
 </script>